using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000209 RID: 521
	internal enum IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04000878 RID: 2168
		IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
