using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.Security.Permissions;
using System.Windows.Forms.Layout;

namespace System.Windows.Forms
{
	// Token: 0x0200068E RID: 1678
	public abstract class ToolStripRenderer
	{
		// Token: 0x0600584E RID: 22606 RVA: 0x00140C6B File Offset: 0x0013FC6B
		protected ToolStripRenderer()
		{
		}

		// Token: 0x0600584F RID: 22607 RVA: 0x00140C73 File Offset: 0x0013FC73
		internal ToolStripRenderer(bool isAutoGenerated)
		{
			this.isAutoGenerated = isAutoGenerated;
		}

		// Token: 0x17001257 RID: 4695
		// (get) Token: 0x06005850 RID: 22608 RVA: 0x00140CE4 File Offset: 0x0013FCE4
		private static ColorMatrix DisabledImageColorMatrix
		{
			get
			{
				if (ToolStripRenderer.disabledImageColorMatrix == null)
				{
					float[][] array = new float[5][];
					array[0] = new float[]
					{
						0.2125f,
						0.2125f,
						0.2125f,
						0f,
						0f
					};
					array[1] = new float[]
					{
						0.2577f,
						0.2577f,
						0.2577f,
						0f,
						0f
					};
					array[2] = new float[]
					{
						0.0361f,
						0.0361f,
						0.0361f,
						0f,
						0f
					};
					float[][] array2 = array;
					int num = 3;
					float[] array3 = new float[5];
					array3[3] = 1f;
					array2[num] = array3;
					array[4] = new float[]
					{
						0.38f,
						0.38f,
						0.38f,
						0f,
						1f
					};
					float[][] array4 = new float[5][];
					float[][] array5 = array4;
					int num2 = 0;
					float[] array6 = new float[5];
					array6[0] = 1f;
					array5[num2] = array6;
					float[][] array7 = array4;
					int num3 = 1;
					float[] array8 = new float[5];
					array8[1] = 1f;
					array7[num3] = array8;
					float[][] array9 = array4;
					int num4 = 2;
					float[] array10 = new float[5];
					array10[2] = 1f;
					array9[num4] = array10;
					float[][] array11 = array4;
					int num5 = 3;
					float[] array12 = new float[5];
					array12[3] = 0.7f;
					array11[num5] = array12;
					float[][] array13 = array4;
					int num6 = 4;
					float[] array14 = new float[5];
					array13[num6] = array14;
					ToolStripRenderer.disabledImageColorMatrix = ControlPaint.MultiplyColorMatrix(array4, array);
				}
				return ToolStripRenderer.disabledImageColorMatrix;
			}
		}

		// Token: 0x17001258 RID: 4696
		// (get) Token: 0x06005851 RID: 22609 RVA: 0x00140DDF File Offset: 0x0013FDDF
		private EventHandlerList Events
		{
			get
			{
				if (this.events == null)
				{
					this.events = new EventHandlerList();
				}
				return this.events;
			}
		}

		// Token: 0x17001259 RID: 4697
		// (get) Token: 0x06005852 RID: 22610 RVA: 0x00140DFA File Offset: 0x0013FDFA
		internal bool IsAutoGenerated
		{
			get
			{
				return this.isAutoGenerated;
			}
		}

		// Token: 0x1700125A RID: 4698
		// (get) Token: 0x06005853 RID: 22611 RVA: 0x00140E02 File Offset: 0x0013FE02
		internal virtual ToolStripRenderer RendererOverride
		{
			get
			{
				return null;
			}
		}

		// Token: 0x1400034B RID: 843
		// (add) Token: 0x06005854 RID: 22612 RVA: 0x00140E05 File Offset: 0x0013FE05
		// (remove) Token: 0x06005855 RID: 22613 RVA: 0x00140E13 File Offset: 0x0013FE13
		public event ToolStripArrowRenderEventHandler RenderArrow
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderArrow, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderArrow, value);
			}
		}

		// Token: 0x1400034C RID: 844
		// (add) Token: 0x06005856 RID: 22614 RVA: 0x00140E21 File Offset: 0x0013FE21
		// (remove) Token: 0x06005857 RID: 22615 RVA: 0x00140E2F File Offset: 0x0013FE2F
		public event ToolStripRenderEventHandler RenderToolStripBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripBackground, value);
			}
		}

		// Token: 0x1400034D RID: 845
		// (add) Token: 0x06005858 RID: 22616 RVA: 0x00140E3D File Offset: 0x0013FE3D
		// (remove) Token: 0x06005859 RID: 22617 RVA: 0x00140E4B File Offset: 0x0013FE4B
		public event ToolStripPanelRenderEventHandler RenderToolStripPanelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripPanelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripPanelBackground, value);
			}
		}

		// Token: 0x1400034E RID: 846
		// (add) Token: 0x0600585A RID: 22618 RVA: 0x00140E59 File Offset: 0x0013FE59
		// (remove) Token: 0x0600585B RID: 22619 RVA: 0x00140E67 File Offset: 0x0013FE67
		public event ToolStripContentPanelRenderEventHandler RenderToolStripContentPanelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripContentPanelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripContentPanelBackground, value);
			}
		}

		// Token: 0x1400034F RID: 847
		// (add) Token: 0x0600585C RID: 22620 RVA: 0x00140E75 File Offset: 0x0013FE75
		// (remove) Token: 0x0600585D RID: 22621 RVA: 0x00140E83 File Offset: 0x0013FE83
		public event ToolStripRenderEventHandler RenderToolStripBorder
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderBorder, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderBorder, value);
			}
		}

		// Token: 0x14000350 RID: 848
		// (add) Token: 0x0600585E RID: 22622 RVA: 0x00140E91 File Offset: 0x0013FE91
		// (remove) Token: 0x0600585F RID: 22623 RVA: 0x00140E9F File Offset: 0x0013FE9F
		public event ToolStripItemRenderEventHandler RenderButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderButtonBackground, value);
			}
		}

		// Token: 0x14000351 RID: 849
		// (add) Token: 0x06005860 RID: 22624 RVA: 0x00140EAD File Offset: 0x0013FEAD
		// (remove) Token: 0x06005861 RID: 22625 RVA: 0x00140EBB File Offset: 0x0013FEBB
		public event ToolStripItemRenderEventHandler RenderDropDownButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderDropDownButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderDropDownButtonBackground, value);
			}
		}

		// Token: 0x14000352 RID: 850
		// (add) Token: 0x06005862 RID: 22626 RVA: 0x00140EC9 File Offset: 0x0013FEC9
		// (remove) Token: 0x06005863 RID: 22627 RVA: 0x00140ED7 File Offset: 0x0013FED7
		public event ToolStripItemRenderEventHandler RenderOverflowButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderOverflowButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderOverflowButtonBackground, value);
			}
		}

		// Token: 0x14000353 RID: 851
		// (add) Token: 0x06005864 RID: 22628 RVA: 0x00140EE5 File Offset: 0x0013FEE5
		// (remove) Token: 0x06005865 RID: 22629 RVA: 0x00140EF3 File Offset: 0x0013FEF3
		public event ToolStripGripRenderEventHandler RenderGrip
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderGrip, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderGrip, value);
			}
		}

		// Token: 0x14000354 RID: 852
		// (add) Token: 0x06005866 RID: 22630 RVA: 0x00140F01 File Offset: 0x0013FF01
		// (remove) Token: 0x06005867 RID: 22631 RVA: 0x00140F0F File Offset: 0x0013FF0F
		public event ToolStripItemRenderEventHandler RenderItemBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemBackground, value);
			}
		}

		// Token: 0x14000355 RID: 853
		// (add) Token: 0x06005868 RID: 22632 RVA: 0x00140F1D File Offset: 0x0013FF1D
		// (remove) Token: 0x06005869 RID: 22633 RVA: 0x00140F2B File Offset: 0x0013FF2B
		public event ToolStripItemImageRenderEventHandler RenderItemImage
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemImage, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemImage, value);
			}
		}

		// Token: 0x14000356 RID: 854
		// (add) Token: 0x0600586A RID: 22634 RVA: 0x00140F39 File Offset: 0x0013FF39
		// (remove) Token: 0x0600586B RID: 22635 RVA: 0x00140F47 File Offset: 0x0013FF47
		public event ToolStripItemImageRenderEventHandler RenderItemCheck
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemCheck, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemCheck, value);
			}
		}

		// Token: 0x14000357 RID: 855
		// (add) Token: 0x0600586C RID: 22636 RVA: 0x00140F55 File Offset: 0x0013FF55
		// (remove) Token: 0x0600586D RID: 22637 RVA: 0x00140F63 File Offset: 0x0013FF63
		public event ToolStripItemTextRenderEventHandler RenderItemText
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderItemText, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderItemText, value);
			}
		}

		// Token: 0x14000358 RID: 856
		// (add) Token: 0x0600586E RID: 22638 RVA: 0x00140F71 File Offset: 0x0013FF71
		// (remove) Token: 0x0600586F RID: 22639 RVA: 0x00140F7F File Offset: 0x0013FF7F
		public event ToolStripRenderEventHandler RenderImageMargin
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderImageMargin, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderImageMargin, value);
			}
		}

		// Token: 0x14000359 RID: 857
		// (add) Token: 0x06005870 RID: 22640 RVA: 0x00140F8D File Offset: 0x0013FF8D
		// (remove) Token: 0x06005871 RID: 22641 RVA: 0x00140F9B File Offset: 0x0013FF9B
		public event ToolStripItemRenderEventHandler RenderLabelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderLabelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderLabelBackground, value);
			}
		}

		// Token: 0x1400035A RID: 858
		// (add) Token: 0x06005872 RID: 22642 RVA: 0x00140FA9 File Offset: 0x0013FFA9
		// (remove) Token: 0x06005873 RID: 22643 RVA: 0x00140FB7 File Offset: 0x0013FFB7
		public event ToolStripItemRenderEventHandler RenderMenuItemBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderMenuItemBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderMenuItemBackground, value);
			}
		}

		// Token: 0x1400035B RID: 859
		// (add) Token: 0x06005874 RID: 22644 RVA: 0x00140FC5 File Offset: 0x0013FFC5
		// (remove) Token: 0x06005875 RID: 22645 RVA: 0x00140FD3 File Offset: 0x0013FFD3
		public event ToolStripItemRenderEventHandler RenderToolStripStatusLabelBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderToolStripStatusLabelBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderToolStripStatusLabelBackground, value);
			}
		}

		// Token: 0x1400035C RID: 860
		// (add) Token: 0x06005876 RID: 22646 RVA: 0x00140FE1 File Offset: 0x0013FFE1
		// (remove) Token: 0x06005877 RID: 22647 RVA: 0x00140FEF File Offset: 0x0013FFEF
		public event ToolStripRenderEventHandler RenderStatusStripSizingGrip
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderStatusStripSizingGrip, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderStatusStripSizingGrip, value);
			}
		}

		// Token: 0x1400035D RID: 861
		// (add) Token: 0x06005878 RID: 22648 RVA: 0x00140FFD File Offset: 0x0013FFFD
		// (remove) Token: 0x06005879 RID: 22649 RVA: 0x0014100B File Offset: 0x0014000B
		public event ToolStripItemRenderEventHandler RenderSplitButtonBackground
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderSplitButtonBackground, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderSplitButtonBackground, value);
			}
		}

		// Token: 0x1400035E RID: 862
		// (add) Token: 0x0600587A RID: 22650 RVA: 0x00141019 File Offset: 0x00140019
		// (remove) Token: 0x0600587B RID: 22651 RVA: 0x00141027 File Offset: 0x00140027
		public event ToolStripSeparatorRenderEventHandler RenderSeparator
		{
			add
			{
				this.AddHandler(ToolStripRenderer.EventRenderSeparator, value);
			}
			remove
			{
				this.RemoveHandler(ToolStripRenderer.EventRenderSeparator, value);
			}
		}

		// Token: 0x0600587C RID: 22652 RVA: 0x00141035 File Offset: 0x00140035
		[UIPermission(SecurityAction.Demand, Window = UIPermissionWindow.AllWindows)]
		private void AddHandler(object key, Delegate value)
		{
			this.Events.AddHandler(key, value);
		}

		// Token: 0x0600587D RID: 22653 RVA: 0x00141044 File Offset: 0x00140044
		[UIPermission(SecurityAction.Demand, Window = UIPermissionWindow.AllWindows)]
		private void RemoveHandler(object key, Delegate value)
		{
			this.Events.RemoveHandler(key, value);
		}

		// Token: 0x0600587E RID: 22654 RVA: 0x00141054 File Offset: 0x00140054
		public static Image CreateDisabledImage(Image normalImage)
		{
			ImageAttributes imageAttributes = new ImageAttributes();
			imageAttributes.ClearColorKey();
			imageAttributes.SetColorMatrix(ToolStripRenderer.DisabledImageColorMatrix);
			Size size = normalImage.Size;
			Bitmap bitmap = new Bitmap(size.Width, size.Height);
			Graphics graphics = Graphics.FromImage(bitmap);
			graphics.DrawImage(normalImage, new Rectangle(0, 0, size.Width, size.Height), 0, 0, size.Width, size.Height, GraphicsUnit.Pixel, imageAttributes);
			graphics.Dispose();
			return bitmap;
		}

		// Token: 0x0600587F RID: 22655 RVA: 0x001410D0 File Offset: 0x001400D0
		public void DrawArrow(ToolStripArrowRenderEventArgs e)
		{
			this.OnRenderArrow(e);
			ToolStripArrowRenderEventHandler toolStripArrowRenderEventHandler = this.Events[ToolStripRenderer.EventRenderArrow] as ToolStripArrowRenderEventHandler;
			if (toolStripArrowRenderEventHandler != null)
			{
				toolStripArrowRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005880 RID: 22656 RVA: 0x00141108 File Offset: 0x00140108
		public void DrawToolStripBackground(ToolStripRenderEventArgs e)
		{
			this.OnRenderToolStripBackground(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripBackground] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005881 RID: 22657 RVA: 0x00141140 File Offset: 0x00140140
		public void DrawGrip(ToolStripGripRenderEventArgs e)
		{
			this.OnRenderGrip(e);
			ToolStripGripRenderEventHandler toolStripGripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderGrip] as ToolStripGripRenderEventHandler;
			if (toolStripGripRenderEventHandler != null)
			{
				toolStripGripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005882 RID: 22658 RVA: 0x00141178 File Offset: 0x00140178
		public void DrawItemBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderItemBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005883 RID: 22659 RVA: 0x001411B0 File Offset: 0x001401B0
		public void DrawImageMargin(ToolStripRenderEventArgs e)
		{
			this.OnRenderImageMargin(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderImageMargin] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005884 RID: 22660 RVA: 0x001411E8 File Offset: 0x001401E8
		public void DrawLabelBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderLabelBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderLabelBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005885 RID: 22661 RVA: 0x00141220 File Offset: 0x00140220
		public void DrawButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005886 RID: 22662 RVA: 0x00141258 File Offset: 0x00140258
		public void DrawToolStripBorder(ToolStripRenderEventArgs e)
		{
			this.OnRenderToolStripBorder(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderBorder] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005887 RID: 22663 RVA: 0x00141290 File Offset: 0x00140290
		public void DrawDropDownButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderDropDownButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderDropDownButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005888 RID: 22664 RVA: 0x001412C8 File Offset: 0x001402C8
		public void DrawOverflowButtonBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderOverflowButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderOverflowButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005889 RID: 22665 RVA: 0x00141300 File Offset: 0x00140300
		public void DrawItemImage(ToolStripItemImageRenderEventArgs e)
		{
			this.OnRenderItemImage(e);
			ToolStripItemImageRenderEventHandler toolStripItemImageRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemImage] as ToolStripItemImageRenderEventHandler;
			if (toolStripItemImageRenderEventHandler != null)
			{
				toolStripItemImageRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600588A RID: 22666 RVA: 0x00141338 File Offset: 0x00140338
		public void DrawItemCheck(ToolStripItemImageRenderEventArgs e)
		{
			this.OnRenderItemCheck(e);
			ToolStripItemImageRenderEventHandler toolStripItemImageRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemCheck] as ToolStripItemImageRenderEventHandler;
			if (toolStripItemImageRenderEventHandler != null)
			{
				toolStripItemImageRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600588B RID: 22667 RVA: 0x00141370 File Offset: 0x00140370
		public void DrawItemText(ToolStripItemTextRenderEventArgs e)
		{
			this.OnRenderItemText(e);
			ToolStripItemTextRenderEventHandler toolStripItemTextRenderEventHandler = this.Events[ToolStripRenderer.EventRenderItemText] as ToolStripItemTextRenderEventHandler;
			if (toolStripItemTextRenderEventHandler != null)
			{
				toolStripItemTextRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600588C RID: 22668 RVA: 0x001413A8 File Offset: 0x001403A8
		public void DrawMenuItemBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderMenuItemBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderMenuItemBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600588D RID: 22669 RVA: 0x001413E0 File Offset: 0x001403E0
		public void DrawSplitButton(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderSplitButtonBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderSplitButtonBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600588E RID: 22670 RVA: 0x00141418 File Offset: 0x00140418
		public void DrawToolStripStatusLabelBackground(ToolStripItemRenderEventArgs e)
		{
			this.OnRenderToolStripStatusLabelBackground(e);
			ToolStripItemRenderEventHandler toolStripItemRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripStatusLabelBackground] as ToolStripItemRenderEventHandler;
			if (toolStripItemRenderEventHandler != null)
			{
				toolStripItemRenderEventHandler(this, e);
			}
		}

		// Token: 0x0600588F RID: 22671 RVA: 0x00141450 File Offset: 0x00140450
		public void DrawStatusStripSizingGrip(ToolStripRenderEventArgs e)
		{
			this.OnRenderStatusStripSizingGrip(e);
			ToolStripRenderEventHandler toolStripRenderEventHandler = this.Events[ToolStripRenderer.EventRenderStatusStripSizingGrip] as ToolStripRenderEventHandler;
			if (toolStripRenderEventHandler != null)
			{
				toolStripRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005890 RID: 22672 RVA: 0x00141488 File Offset: 0x00140488
		public void DrawSeparator(ToolStripSeparatorRenderEventArgs e)
		{
			this.OnRenderSeparator(e);
			ToolStripSeparatorRenderEventHandler toolStripSeparatorRenderEventHandler = this.Events[ToolStripRenderer.EventRenderSeparator] as ToolStripSeparatorRenderEventHandler;
			if (toolStripSeparatorRenderEventHandler != null)
			{
				toolStripSeparatorRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005891 RID: 22673 RVA: 0x001414C0 File Offset: 0x001404C0
		public void DrawToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
		{
			this.OnRenderToolStripPanelBackground(e);
			ToolStripPanelRenderEventHandler toolStripPanelRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripPanelBackground] as ToolStripPanelRenderEventHandler;
			if (toolStripPanelRenderEventHandler != null)
			{
				toolStripPanelRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005892 RID: 22674 RVA: 0x001414F8 File Offset: 0x001404F8
		public void DrawToolStripContentPanelBackground(ToolStripContentPanelRenderEventArgs e)
		{
			this.OnRenderToolStripContentPanelBackground(e);
			ToolStripContentPanelRenderEventHandler toolStripContentPanelRenderEventHandler = this.Events[ToolStripRenderer.EventRenderToolStripContentPanelBackground] as ToolStripContentPanelRenderEventHandler;
			if (toolStripContentPanelRenderEventHandler != null)
			{
				toolStripContentPanelRenderEventHandler(this, e);
			}
		}

		// Token: 0x06005893 RID: 22675 RVA: 0x0014152D File Offset: 0x0014052D
		internal virtual Region GetTransparentRegion(ToolStrip toolStrip)
		{
			return null;
		}

		// Token: 0x06005894 RID: 22676 RVA: 0x00141530 File Offset: 0x00140530
		protected internal virtual void Initialize(ToolStrip toolStrip)
		{
		}

		// Token: 0x06005895 RID: 22677 RVA: 0x00141532 File Offset: 0x00140532
		protected internal virtual void InitializePanel(ToolStripPanel toolStripPanel)
		{
		}

		// Token: 0x06005896 RID: 22678 RVA: 0x00141534 File Offset: 0x00140534
		protected internal virtual void InitializeContentPanel(ToolStripContentPanel contentPanel)
		{
		}

		// Token: 0x06005897 RID: 22679 RVA: 0x00141536 File Offset: 0x00140536
		protected internal virtual void InitializeItem(ToolStripItem item)
		{
		}

		// Token: 0x06005898 RID: 22680 RVA: 0x00141538 File Offset: 0x00140538
		protected virtual void OnRenderArrow(ToolStripArrowRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderArrow(e);
				return;
			}
			Graphics graphics = e.Graphics;
			Rectangle arrowRectangle = e.ArrowRectangle;
			using (Brush brush = new SolidBrush(e.ArrowColor))
			{
				Point point = new Point(arrowRectangle.Left + arrowRectangle.Width / 2, arrowRectangle.Top + arrowRectangle.Height / 2);
				ArrowDirection direction = e.Direction;
				Point[] points;
				switch (direction)
				{
				case ArrowDirection.Left:
					points = new Point[]
					{
						new Point(point.X + 2, point.Y - 4),
						new Point(point.X + 2, point.Y + 4),
						new Point(point.X - 2, point.Y)
					};
					break;
				case ArrowDirection.Up:
					points = new Point[]
					{
						new Point(point.X - 2, point.Y + 1),
						new Point(point.X + 3, point.Y + 1),
						new Point(point.X, point.Y - 2)
					};
					break;
				default:
					switch (direction)
					{
					case ArrowDirection.Right:
						points = new Point[]
						{
							new Point(point.X - 2, point.Y - 4),
							new Point(point.X - 2, point.Y + 4),
							new Point(point.X + 2, point.Y)
						};
						goto IL_26D;
					}
					points = new Point[]
					{
						new Point(point.X - 2, point.Y - 1),
						new Point(point.X + 3, point.Y - 1),
						new Point(point.X, point.Y + 2)
					};
					break;
				}
				IL_26D:
				graphics.FillPolygon(brush, points);
			}
		}

		// Token: 0x06005899 RID: 22681 RVA: 0x001417E4 File Offset: 0x001407E4
		protected virtual void OnRenderToolStripBackground(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripBackground(e);
			}
		}

		// Token: 0x0600589A RID: 22682 RVA: 0x001417FA File Offset: 0x001407FA
		protected virtual void OnRenderToolStripBorder(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripBorder(e);
			}
		}

		// Token: 0x0600589B RID: 22683 RVA: 0x00141810 File Offset: 0x00140810
		protected virtual void OnRenderGrip(ToolStripGripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderGrip(e);
			}
		}

		// Token: 0x0600589C RID: 22684 RVA: 0x00141826 File Offset: 0x00140826
		protected virtual void OnRenderItemBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemBackground(e);
			}
		}

		// Token: 0x0600589D RID: 22685 RVA: 0x0014183C File Offset: 0x0014083C
		protected virtual void OnRenderImageMargin(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderImageMargin(e);
			}
		}

		// Token: 0x0600589E RID: 22686 RVA: 0x00141852 File Offset: 0x00140852
		protected virtual void OnRenderButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderButtonBackground(e);
			}
		}

		// Token: 0x0600589F RID: 22687 RVA: 0x00141868 File Offset: 0x00140868
		protected virtual void OnRenderDropDownButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderDropDownButtonBackground(e);
			}
		}

		// Token: 0x060058A0 RID: 22688 RVA: 0x0014187E File Offset: 0x0014087E
		protected virtual void OnRenderOverflowButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderOverflowButtonBackground(e);
			}
		}

		// Token: 0x060058A1 RID: 22689 RVA: 0x00141894 File Offset: 0x00140894
		protected virtual void OnRenderItemImage(ToolStripItemImageRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemImage(e);
				return;
			}
			Rectangle imageRectangle = e.ImageRectangle;
			Image image = e.Image;
			if (imageRectangle != Rectangle.Empty && image != null)
			{
				bool flag = false;
				if (e.ShiftOnPress && e.Item.Pressed)
				{
					imageRectangle.X++;
				}
				if (!e.Item.Enabled)
				{
					image = ToolStripRenderer.CreateDisabledImage(image);
					flag = true;
				}
				if (e.Item.ImageScaling == ToolStripItemImageScaling.None)
				{
					e.Graphics.DrawImage(image, imageRectangle, new Rectangle(Point.Empty, imageRectangle.Size), GraphicsUnit.Pixel);
				}
				else
				{
					e.Graphics.DrawImage(image, imageRectangle);
				}
				if (flag)
				{
					image.Dispose();
				}
			}
		}

		// Token: 0x060058A2 RID: 22690 RVA: 0x0014195C File Offset: 0x0014095C
		protected virtual void OnRenderItemCheck(ToolStripItemImageRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemCheck(e);
				return;
			}
			Rectangle imageRectangle = e.ImageRectangle;
			Image image = e.Image;
			if (imageRectangle != Rectangle.Empty && image != null)
			{
				if (!e.Item.Enabled)
				{
					image = ToolStripRenderer.CreateDisabledImage(image);
				}
				e.Graphics.DrawImage(image, imageRectangle, new Rectangle(Point.Empty, imageRectangle.Size), GraphicsUnit.Pixel);
			}
		}

		// Token: 0x060058A3 RID: 22691 RVA: 0x001419D0 File Offset: 0x001409D0
		protected virtual void OnRenderItemText(ToolStripItemTextRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderItemText(e);
				return;
			}
			ToolStripItem item = e.Item;
			Graphics graphics = e.Graphics;
			Color color = e.TextColor;
			Font textFont = e.TextFont;
			string text = e.Text;
			Rectangle textRectangle = e.TextRectangle;
			TextFormatFlags textFormat = e.TextFormat;
			color = (item.Enabled ? color : SystemColors.GrayText);
			if (e.TextDirection != ToolStripTextDirection.Horizontal && textRectangle.Width > 0 && textRectangle.Height > 0)
			{
				Size size = LayoutUtils.FlipSize(textRectangle.Size);
				using (Bitmap bitmap = new Bitmap(size.Width, size.Height, PixelFormat.Format32bppPArgb))
				{
					using (Graphics graphics2 = Graphics.FromImage(bitmap))
					{
						graphics2.TextRenderingHint = TextRenderingHint.AntiAlias;
						TextRenderer.DrawText(graphics2, text, textFont, new Rectangle(Point.Empty, size), color, textFormat);
						bitmap.RotateFlip((e.TextDirection == ToolStripTextDirection.Vertical90) ? RotateFlipType.Rotate90FlipNone : RotateFlipType.Rotate270FlipNone);
						graphics.DrawImage(bitmap, textRectangle);
					}
					return;
				}
			}
			TextRenderer.DrawText(graphics, text, textFont, textRectangle, color, textFormat);
		}

		// Token: 0x060058A4 RID: 22692 RVA: 0x00141B14 File Offset: 0x00140B14
		protected virtual void OnRenderLabelBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderLabelBackground(e);
			}
		}

		// Token: 0x060058A5 RID: 22693 RVA: 0x00141B2A File Offset: 0x00140B2A
		protected virtual void OnRenderMenuItemBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderMenuItemBackground(e);
			}
		}

		// Token: 0x060058A6 RID: 22694 RVA: 0x00141B40 File Offset: 0x00140B40
		protected virtual void OnRenderSeparator(ToolStripSeparatorRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderSeparator(e);
			}
		}

		// Token: 0x060058A7 RID: 22695 RVA: 0x00141B56 File Offset: 0x00140B56
		protected virtual void OnRenderToolStripPanelBackground(ToolStripPanelRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripPanelBackground(e);
			}
		}

		// Token: 0x060058A8 RID: 22696 RVA: 0x00141B6C File Offset: 0x00140B6C
		protected virtual void OnRenderToolStripContentPanelBackground(ToolStripContentPanelRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripContentPanelBackground(e);
			}
		}

		// Token: 0x060058A9 RID: 22697 RVA: 0x00141B82 File Offset: 0x00140B82
		protected virtual void OnRenderToolStripStatusLabelBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderToolStripStatusLabelBackground(e);
			}
		}

		// Token: 0x060058AA RID: 22698 RVA: 0x00141B98 File Offset: 0x00140B98
		protected virtual void OnRenderStatusStripSizingGrip(ToolStripRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderStatusStripSizingGrip(e);
				return;
			}
			Graphics graphics = e.Graphics;
			StatusStrip statusStrip = e.ToolStrip as StatusStrip;
			if (statusStrip != null)
			{
				Rectangle sizeGripBounds = statusStrip.SizeGripBounds;
				if (!LayoutUtils.IsZeroWidthOrHeight(sizeGripBounds))
				{
					Rectangle[] array = new Rectangle[ToolStripRenderer.baseSizeGripRectangles.Length];
					Rectangle[] array2 = new Rectangle[ToolStripRenderer.baseSizeGripRectangles.Length];
					for (int i = 0; i < ToolStripRenderer.baseSizeGripRectangles.Length; i++)
					{
						Rectangle rectangle = ToolStripRenderer.baseSizeGripRectangles[i];
						if (statusStrip.RightToLeft == RightToLeft.Yes)
						{
							rectangle.X = sizeGripBounds.Width - rectangle.X - rectangle.Width;
						}
						rectangle.Offset(sizeGripBounds.X, sizeGripBounds.Bottom - 12);
						array[i] = rectangle;
						if (statusStrip.RightToLeft == RightToLeft.Yes)
						{
							rectangle.Offset(1, -1);
						}
						else
						{
							rectangle.Offset(-1, -1);
						}
						array2[i] = rectangle;
					}
					graphics.FillRectangles(SystemBrushes.ButtonHighlight, array);
					graphics.FillRectangles(SystemBrushes.ButtonShadow, array2);
				}
			}
		}

		// Token: 0x060058AB RID: 22699 RVA: 0x00141CC3 File Offset: 0x00140CC3
		protected virtual void OnRenderSplitButtonBackground(ToolStripItemRenderEventArgs e)
		{
			if (this.RendererOverride != null)
			{
				this.RendererOverride.OnRenderSplitButtonBackground(e);
			}
		}

		// Token: 0x060058AC RID: 22700 RVA: 0x00141CD9 File Offset: 0x00140CD9
		internal bool ShouldPaintBackground(Control control)
		{
			return control.RawBackColor == Color.Empty && control.BackgroundImage == null;
		}

		// Token: 0x04003805 RID: 14341
		private static readonly object EventRenderSplitButtonBackground = new object();

		// Token: 0x04003806 RID: 14342
		private static readonly object EventRenderItemBackground = new object();

		// Token: 0x04003807 RID: 14343
		private static readonly object EventRenderItemImage = new object();

		// Token: 0x04003808 RID: 14344
		private static readonly object EventRenderItemText = new object();

		// Token: 0x04003809 RID: 14345
		private static readonly object EventRenderToolStripBackground = new object();

		// Token: 0x0400380A RID: 14346
		private static readonly object EventRenderGrip = new object();

		// Token: 0x0400380B RID: 14347
		private static readonly object EventRenderButtonBackground = new object();

		// Token: 0x0400380C RID: 14348
		private static readonly object EventRenderLabelBackground = new object();

		// Token: 0x0400380D RID: 14349
		private static readonly object EventRenderMenuItemBackground = new object();

		// Token: 0x0400380E RID: 14350
		private static readonly object EventRenderDropDownButtonBackground = new object();

		// Token: 0x0400380F RID: 14351
		private static readonly object EventRenderOverflowButtonBackground = new object();

		// Token: 0x04003810 RID: 14352
		private static readonly object EventRenderImageMargin = new object();

		// Token: 0x04003811 RID: 14353
		private static readonly object EventRenderBorder = new object();

		// Token: 0x04003812 RID: 14354
		private static readonly object EventRenderArrow = new object();

		// Token: 0x04003813 RID: 14355
		private static readonly object EventRenderStatusStripPanelBackground = new object();

		// Token: 0x04003814 RID: 14356
		private static readonly object EventRenderToolStripStatusLabelBackground = new object();

		// Token: 0x04003815 RID: 14357
		private static readonly object EventRenderSeparator = new object();

		// Token: 0x04003816 RID: 14358
		private static readonly object EventRenderItemCheck = new object();

		// Token: 0x04003817 RID: 14359
		private static readonly object EventRenderToolStripPanelBackground = new object();

		// Token: 0x04003818 RID: 14360
		private static readonly object EventRenderToolStripContentPanelBackground = new object();

		// Token: 0x04003819 RID: 14361
		private static readonly object EventRenderStatusStripSizingGrip = new object();

		// Token: 0x0400381A RID: 14362
		private static ColorMatrix disabledImageColorMatrix;

		// Token: 0x0400381B RID: 14363
		private EventHandlerList events;

		// Token: 0x0400381C RID: 14364
		private bool isAutoGenerated;

		// Token: 0x0400381D RID: 14365
		private static Rectangle[] baseSizeGripRectangles = new Rectangle[]
		{
			new Rectangle(8, 0, 2, 2),
			new Rectangle(8, 4, 2, 2),
			new Rectangle(8, 8, 2, 2),
			new Rectangle(4, 4, 2, 2),
			new Rectangle(4, 8, 2, 2),
			new Rectangle(0, 8, 2, 2)
		};
	}
}
