using System;
using System.Collections.Specialized;
using System.ComponentModel;

namespace System.Windows.Forms
{
	// Token: 0x020006D5 RID: 1749
	internal class ToolStripRendererSwitcher
	{
		// Token: 0x06005C5E RID: 23646 RVA: 0x00150465 File Offset: 0x0014F465
		public ToolStripRendererSwitcher(Control owner, ToolStripRenderMode defaultRenderMode) : this(owner)
		{
			this.defaultRenderMode = defaultRenderMode;
			this.RenderMode = defaultRenderMode;
		}

		// Token: 0x06005C5F RID: 23647 RVA: 0x0015047C File Offset: 0x0014F47C
		public ToolStripRendererSwitcher(Control owner)
		{
			this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = true;
			this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
			owner.Disposed += this.OnControlDisposed;
			owner.VisibleChanged += this.OnControlVisibleChanged;
			if (owner.Visible)
			{
				this.OnControlVisibleChanged(owner, EventArgs.Empty);
			}
		}

		// Token: 0x17001354 RID: 4948
		// (get) Token: 0x06005C60 RID: 23648 RVA: 0x0015050C File Offset: 0x0014F50C
		// (set) Token: 0x06005C61 RID: 23649 RVA: 0x00150558 File Offset: 0x0014F558
		public ToolStripRenderer Renderer
		{
			get
			{
				if (this.RenderMode == ToolStripRenderMode.ManagerRenderMode)
				{
					return ToolStripManager.Renderer;
				}
				this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = false;
				if (this.renderer == null)
				{
					this.Renderer = ToolStripManager.CreateRenderer(this.RenderMode);
				}
				return this.renderer;
			}
			set
			{
				if (this.renderer != value)
				{
					this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = (value == null);
					this.renderer = value;
					this.currentRendererType = ((this.renderer != null) ? this.renderer.GetType() : typeof(Type));
					this.OnRendererChanged(EventArgs.Empty);
				}
			}
		}

		// Token: 0x17001355 RID: 4949
		// (get) Token: 0x06005C62 RID: 23650 RVA: 0x001505BC File Offset: 0x0014F5BC
		// (set) Token: 0x06005C63 RID: 23651 RVA: 0x00150614 File Offset: 0x0014F614
		public ToolStripRenderMode RenderMode
		{
			get
			{
				if (this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
				{
					return ToolStripRenderMode.ManagerRenderMode;
				}
				if (this.renderer != null && !this.renderer.IsAutoGenerated)
				{
					return ToolStripRenderMode.Custom;
				}
				if (this.currentRendererType == ToolStripManager.ProfessionalRendererType)
				{
					return ToolStripRenderMode.Professional;
				}
				if (this.currentRendererType == ToolStripManager.SystemRendererType)
				{
					return ToolStripRenderMode.System;
				}
				return ToolStripRenderMode.Custom;
			}
			set
			{
				if (!ClientUtils.IsEnumValid(value, (int)value, 0, 3))
				{
					throw new InvalidEnumArgumentException("value", (int)value, typeof(ToolStripRenderMode));
				}
				if (value == ToolStripRenderMode.Custom)
				{
					throw new NotSupportedException(SR.GetString("ToolStripRenderModeUseRendererPropertyInstead"));
				}
				if (value == ToolStripRenderMode.ManagerRenderMode)
				{
					if (!this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
					{
						this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = true;
						this.OnRendererChanged(EventArgs.Empty);
						return;
					}
				}
				else
				{
					this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer] = false;
					this.Renderer = ToolStripManager.CreateRenderer(value);
				}
			}
		}

		// Token: 0x1400037D RID: 893
		// (add) Token: 0x06005C64 RID: 23652 RVA: 0x001506AA File Offset: 0x0014F6AA
		// (remove) Token: 0x06005C65 RID: 23653 RVA: 0x001506C3 File Offset: 0x0014F6C3
		public event EventHandler RendererChanged;

		// Token: 0x06005C66 RID: 23654 RVA: 0x001506DC File Offset: 0x0014F6DC
		private void OnRendererChanged(EventArgs e)
		{
			if (this.RendererChanged != null)
			{
				this.RendererChanged(this, e);
			}
		}

		// Token: 0x06005C67 RID: 23655 RVA: 0x001506F3 File Offset: 0x0014F6F3
		private void OnDefaultRendererChanged(object sender, EventArgs e)
		{
			if (this.state[ToolStripRendererSwitcher.stateUseDefaultRenderer])
			{
				this.OnRendererChanged(e);
			}
		}

		// Token: 0x06005C68 RID: 23656 RVA: 0x0015070E File Offset: 0x0014F70E
		private void OnControlDisposed(object sender, EventArgs e)
		{
			if (this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
			{
				ToolStripManager.RendererChanged -= this.OnDefaultRendererChanged;
				this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
			}
		}

		// Token: 0x06005C69 RID: 23657 RVA: 0x00150744 File Offset: 0x0014F744
		private void OnControlVisibleChanged(object sender, EventArgs e)
		{
			Control control = sender as Control;
			if (control != null)
			{
				if (control.Visible)
				{
					if (!this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
					{
						ToolStripManager.RendererChanged += this.OnDefaultRendererChanged;
						this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = true;
						return;
					}
				}
				else if (this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged])
				{
					ToolStripManager.RendererChanged -= this.OnDefaultRendererChanged;
					this.state[ToolStripRendererSwitcher.stateAttachedRendererChanged] = false;
				}
			}
		}

		// Token: 0x06005C6A RID: 23658 RVA: 0x001507CC File Offset: 0x0014F7CC
		public bool ShouldSerializeRenderMode()
		{
			return this.RenderMode != this.defaultRenderMode && this.RenderMode != ToolStripRenderMode.Custom;
		}

		// Token: 0x06005C6B RID: 23659 RVA: 0x001507EA File Offset: 0x0014F7EA
		public void ResetRenderMode()
		{
			this.RenderMode = this.defaultRenderMode;
		}

		// Token: 0x0400390F RID: 14607
		private static readonly int stateUseDefaultRenderer = BitVector32.CreateMask();

		// Token: 0x04003910 RID: 14608
		private static readonly int stateAttachedRendererChanged = BitVector32.CreateMask(ToolStripRendererSwitcher.stateUseDefaultRenderer);

		// Token: 0x04003911 RID: 14609
		private ToolStripRenderer renderer;

		// Token: 0x04003912 RID: 14610
		private Type currentRendererType = typeof(Type);

		// Token: 0x04003913 RID: 14611
		private BitVector32 state = default(BitVector32);

		// Token: 0x04003914 RID: 14612
		private ToolStripRenderMode defaultRenderMode = ToolStripRenderMode.ManagerRenderMode;
	}
}
